version: "2"
services:    
    react-client:
        build: ./react-client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./react-client:/react-client
            - /react-client/node_modules
        links:
            - api
        networks: 
            - webappnetwork
    
    angular-client:
        build: ./angular-client
        restart: always
        ports:
            - "4200:4200"
        volumes:
            - ./angular-client:/angular-client
            - /angular-client/node_modules
        links:
            - api
        networks: 
            - webappnetwork

    api:
        build: ./api 
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./api:/api
            - /api/node_modules
        depends_on:
            - mongodb
        networks: 
            - webappnetwork

    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth --smallfiles
        networks: 
            - webappnetwork

networks:
    webappnetwork:
        driver: bridge